SPMS/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path

from core.views import *

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", ViewPastProjects, name="home"),
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/signup/", SignUp, name="select_signup"),
    path("accounts/signup/student/", StudentSignUp.as_view(), name="student_signup"),
    path(
        "accounts/signup/supervisor/",
        SupervisorSignUp.as_view(),
        name="supervisor_signup",
    ),
    path(
        "appointments/request_appointment",
        RequestAppointment,
        name="request_appointment",
    ),
    path("appointments/update_timeslots", SelectAvailableDays, name="select_days"),
    path(
        "appointments/delete_timeslots(<availableday_id>[0-9]+)(<day>[a-z]+)",
        DeleteAvailableDays,
        name="delete_timeslot",
    ),
    path("appointments/save_days", SaveAvailableDays, name="save_days"),
    path("appointments/view_appointments", ViewAppointments, name="appointments"),
    path(
        "appointments/approved_appointments",
        view_approved_appointments,
        name="approved_appointments",
    ),
    path("appointments/view_available_slots", ViewAvailableDays, name="view_available"),
    path(
        "appointments/approve_appointment(<appointment_id>[0-9]+)",
        ApproveAppointment,
        name="approve_appointment",
    ),
    path(
        "appointments/reject_appointment(<appointment_id>[0-9]+)",
        RejectAppointment,
        name="reject_appointment",
    ),
    path("coordinator/set_schedule", SetSchedule, name="set_schedule"),
    path("coordinator/set_milestone", SetMilestones, name="set_milestone"),
    path("student/profile", ViewProfile, name="student_view_profile"),
    path(
        "student/profile/update_profile", UpdateProfile, name="student_update_profile"
    ),
    path("student/project/create_project", createproject_view, name="create_project"),
    path("student/project", StudentProject, name="student_project"),
    path("supervisor/profile", ViewProfile, name="supervisor_view_profile"),
    path(
        "supervisor/profile/update_profile",
        UpdateProfile,
        name="supervisor_update_profile",
    ),
    path(
        "student/project/upload_document(<milestone_id>[0-9]+)",
        upload_file,
        name="upload_document",
    ),
    path("project/download(<document_id>[0-9]+)", download_document, name="download"),
    path(
        "project/download_abstract(<abstract_id>[0-9]+)",
        download_abstract,
        name="download_abstract",
    ),
    path(
        "project/view_comments(<milestone_id>[0-9]+)(<student_id>[0-9]+)",
        view_comment,
        name="view_comments",
    ),
    path("project/project_schedule", chart_view, name="project_schedule"),
    path("supervisor/project", project_view, name="project"),
    path(
        "supervisor/project_supervision(<student_id>[0-9]+)",
        project_supervision_view,
        name="project_supervision",
    ),
    path(
        "supervisor/project_supervision/close_milestone(<milestone_id>[0-9]+)(<project_id>[0-9]+)",
        CloseMilestone,
        name="close_milestone",
    ),
    path(
        "supervisor/project_supervision/close_project(<project_id>[0-9]+)",
        CloseProject,
        name="close_project",
    ),
    path("view_notifications", view_notifications, name="view_notifications"),
    # path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
    # path("past-projects/", PastProjets, name="projects"),
    # path("accounts/login",include("django.auth.urls")),
]

urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
import datetime

from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils import timezone


class Schedule(models.Model):
    schedule_name = models.CharField(max_length=100, default="")
    start_date = models.DateField(auto_now_add=False, auto_now=False)
    end_date = models.DateField(auto_now_add=False, auto_now=False)
    status = models.BooleanField(default=1)

    def __str__(self):
        return self.schedule_name


class Abstract(models.Model):
    title = models.CharField(max_length=100)
    abstract_text = models.CharField(max_length=1000)
    document = models.FileField(upload_to="abstract/")
    upladed_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


class Project(models.Model):
    title = models.CharField(max_length=100, default="title")
    status = models.BooleanField(default=True)
    start_date = models.DateField(auto_now=False, auto_now_add=True)
    schedule = models.ForeignKey(Schedule, on_delete=models.CASCADE)
    abstract = models.OneToOneField(
        Abstract, on_delete=models.CASCADE, default=None, null=True, blank=True
    )

    def __str__(self):
        return self.title


class User(AbstractUser):
    is_student = models.BooleanField("student_status", default=False)
    is_supervisor = models.BooleanField("supervisor_status", default=False)


class Supervisor(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=20, default="")
    last_name = models.CharField(max_length=20, default="")
    email = models.EmailField(max_length=255, default="")

    def __str__(self):
        return self.first_name + " " + self.last_name


class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=20, default="")
    last_name = models.CharField(max_length=20, default="")
    email = models.EmailField(max_length=255, default="")
    course = models.CharField(max_length=30, default="")
    reg_number = models.CharField(max_length=30, unique=True)
    supervisor = models.ForeignKey(Supervisor, on_delete=models.CASCADE, null=True)
    project = models.OneToOneField(Project, on_delete=models.CASCADE, null=True)
    status = models.BooleanField(default=True)

    def __str__(self):
        return self.first_name + " " + self.last_name


class PastProject(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)

    def __str__(self):
        return self.project.title


class AvailableDay(models.Model):
    monday = models.TimeField(null=True)
    tuesday = models.TimeField(null=True)
    wednesday = models.TimeField(null=True)
    thursday = models.TimeField(null=True)
    friday = models.TimeField(null=True)
    saturday = models.TimeField(null=True)
    sunday = models.TimeField(null=True)
    supervisor = models.ForeignKey(Supervisor, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.supervisor.first_name + " " + self.supervisor.last_name


class Appointment(models.Model):
    supervisor = models.ForeignKey(Supervisor, on_delete=models.CASCADE, null=True)
    student = models.ForeignKey(Student, on_delete=models.CASCADE, null=True)
    date = models.DateField(auto_now=False, auto_now_add=False)
    time = models.TimeField(auto_now=False, auto_now_add=False)

    Approved = "Approved"
    Applied = "Applied"
    Rejected = "Rejected"
    status = ((Approved, "Approved"), (Applied, "Applied"), (Rejected, "Rejected"))
    approved = models.CharField(max_length=10, choices=status, default="Applied")

    def __str__(self):
        return self.approved


class Group(models.Model):
    start_date = models.DateField()
    end_date = models.DateField()
    first_semester = "S1"
    second_semester = "S2"
    milestone_group = (
        (first_semester, "Semester One"),
        (second_semester, "Semester Two"),
    )
    semester = models.CharField(choices=milestone_group, default="S1", max_length=2)

    def __str__(self):
        return self.semester


class Milestone(models.Model):
    Not_Started = "NS"
    Ongoing = "ON"
    Finished = "FN"
    milestone_status = (
        (Not_Started, "Not Started"),
        (Ongoing, "Ongoing"),
        (Finished, "Finished"),
    )
    milestone_name = models.CharField(max_length=100)
    start_date = models.DateField()
    end_date = models.DateField()
    schedule = models.ForeignKey(Schedule, on_delete=models.CASCADE)
    semester = models.ForeignKey(Group, on_delete=models.CASCADE, default=1)
    required_document = models.CharField(max_length=100, null=True)

    # status = models.CharField(max_length=2, choices=milestone_status, default="NS")

    @property
    def check_status(self):
        now = datetime.datetime.now().date()
        if self.end_date < now and now > self.start_date:
            self.status = "FN"
            return "FN"
        elif self.start_date < now and now < self.end_date:
            self.status = "ON"
            return "ON"
        else:
            self.status = "NS"
            return "NS"

    def __str__(self):
        return self.milestone_name


class CompletedMilestones(models.Model):
    milestone = models.ForeignKey(Milestone, on_delete=models.CASCADE)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)


class Document(models.Model):
    title = models.CharField(max_length=50)
    document = models.FileField(upload_to="")
    upladed_at = models.DateTimeField(auto_now_add=True)
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    milestone = models.ForeignKey(Milestone, on_delete=models.CASCADE)

    def __str__(self):
        return self.title


class Comment(models.Model):
    text = models.CharField(max_length=200)
    student = models.ForeignKey(Student, null=False, on_delete=models.CASCADE)
    supervisor = models.ForeignKey(Supervisor, null=False, on_delete=models.CASCADE)
    sender = models.BooleanField(default=0)
    sent_date = models.DateField(auto_now_add=False, auto_now=True)
    milestone = models.ForeignKey(Milestone, null=False, on_delete=models.CASCADE)


class Notification(models.Model):
    receiver_options = (
        ("students", "students"),
        ("supervisors", "supervisors"),
        ("everyone", "everyone"),
    )

    text = models.CharField(max_length=200)
    title = models.CharField(max_length=50, null=True)
    receiver = models.CharField(choices=receiver_options, max_length=255)
    document = models.FileField(upload_to="notifications/", null=True)
    sent_time = models.TimeField(auto_now_add=False, auto_now=True)
    # default=datetime.datetime.now().strftime("%H:%M:%S"))
    sent_date = models.DateField(auto_now_add=False, auto_now=True)
    # default=datetime.date.today().strftime("%Y-%m-%d"))

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.db import transaction

from core.models import *


class StudentSignUpForm(UserCreationForm):
    courses = (
        ("BCA", "Bachelors In Computer Applications (Computer Science)"),
        ("MCA", "Masters In Computer Applications (Computer Science)"),
    )
    first_name = forms.CharField(
        max_length=30,
        required=True,
        help_text="Optional",
        widget=forms.TextInput(attrs={"placeholder": "Write your name here"}),
    )
    last_name = forms.CharField(max_length=30, required=True, help_text="Optional")
    registration_number = forms.CharField(
        max_length=30, required=True, help_text="Required"
    )
    course = forms.ChoiceField(help_text="Required", choices=courses)

    class Meta(UserCreationForm.Meta):
        model = User
        fields = (
            "first_name",
            "last_name",
            "username",
            "email",
            "password1",
            "password2",
            "registration_number",
            "course",
        )

    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.is_student = True
        user.save()
        student = Student.objects.create(
            user=user,
            first_name=user.first_name,
            last_name=user.last_name,
            email=user.email,
            reg_number=self.cleaned_data.get("registration_number"),
            course=self.cleaned_data.get("course"),
        )

        # student.interests.add(*self.cleaned_data.get('interests'))
        return user


class SupervisorSignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=True, help_text="Optional")
    last_name = forms.CharField(max_length=30, required=True, help_text="Optional")

    class Meta(UserCreationForm.Meta):
        model = User
        fields = (
            "first_name",
            "last_name",
            "username",
            "email",
            "password1",
            "password2",
        )

    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.is_supervisor = True
        user.save()
        supervisor = Supervisor.objects.create(
            user=user,
            first_name=user.first_name,
            last_name=user.last_name,
            email=user.email,
        )
        return user


class CreateAppointmentForm(forms.Form):
    date = forms.DateField(input_formats=["%d/%m/%Y %H:%M"])
    time = forms.TimeField(input_formats=["%H:%M"])


class SelectAvailableDaysForm(forms.Form):
    monday = forms.TimeField(
        input_formats="%H:%M",
        widget=forms.TimeInput(
            attrs={
                "class": "form-control datetimepicker-input",
                "data-target": "#datetimepicker1",
            }
        ),
        required=False,
    )
    tuesday = forms.TimeField(
        input_formats=["%H:%M"],
        widget=forms.TimeInput(
            attrs={
                "class": "form-control datetimepicker-input",
                "data-target": "#datetimepicker2",
            }
        ),
        required=False,
    )
    wednesday = forms.TimeField(
        input_formats=["%H:%M"],
        widget=forms.TimeInput(
            attrs={
                "class": "form-control datetimepicker-input",
                "data-target": "#datetimepicker3",
            }
        ),
        required=False,
    )
    thursday = forms.TimeField(
        input_formats=["%H:%M"],
        widget=forms.TimeInput(
            attrs={
                "class": "form-control datetimepicker-input",
                "data-target": "#datetimepicker4",
            }
        ),
        required=False,
    )
    friday = forms.TimeField(
        input_formats=["%H:%M"],
        widget=forms.TimeInput(
            attrs={
                "class": "form-control datetimepicker-input",
                "data-target": "#datetimepicker5",
            }
        ),
        required=False,
    )
    saturday = forms.TimeField(
        input_formats=["%H:%M"],
        widget=forms.TimeInput(
            attrs={
                "class": "form-control datetimepicker-input",
                "data-target": "#datetimepicker6",
            }
        ),
        required=False,
    )
    sunday = forms.TimeField(
        input_formats=["%H:%M"],
        widget=forms.TimeInput(
            attrs={
                "class": "form-control datetimepicker-input",
                "data-target": "#datetimepicker7",
            }
        ),
        required=False,
    )


class SetScheduleForm(forms.Form):
    start_date = forms.DateField(required="False")
    end_date = forms.DateField(required="False")


class SetMilestoneForm(forms.Form):
    milestone = forms.CharField()
    start_date = forms.DateField(required="False")
    end_date = forms.DateField(required="False")


class UploadFileForm(forms.Form):
    title = forms.CharField(max_length=50, required=True)
    document = forms.FileField()


class CreateProjectForm(forms.Form):
    title = forms.CharField(
        max_length=100, required=True, help_text="Enter your Project Title"
    )
    abstract = forms.CharField(
        widget=forms.Textarea(
            attrs={"placeholder": "Type in your project abstract here"}
        ),
        min_length=200,
        max_length=1000,
        required=True,
        help_text="Your abstract should be more than 200 words",
    )
    abstract_document = forms.FileField(
        help_text="Upload your abstract document in a doc or docx format"
    )


class SendCommentForm(forms.Form):
    comment = forms.CharField(
        max_length=200,
        initial="Asas",
        widget=forms.Textarea(
            attrs={"rows": "2", "cols": "30", "placeholder": "Add your comment here"}
        ),
    )


class UpdateProfileForm(forms.Form):
    user = User
    first_name = forms.CharField(
        initial="supervisor", max_length=50, widget=forms.TextInput()
    )
    last_name = forms.CharField(max_length=50)
    user_name = forms.CharField(max_length=50)
    email = forms.EmailField(max_length=50)


class TestForm(forms.Form):
    phone_numbers = forms.CharField(max_length=100, widget=forms.Textarea())
    message = forms.CharField(max_length=100, widget=forms.Textarea())

core/templates/core/dashboard/student/appointments.html
{% extends "core/dashboard/dashboard_base.html" %}

{% block content %}

<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h2 class="page-header">Appointments</h2>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->

    <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <b>Approved Appointments</b>
                    </div>
                    <!-- /.panel-heading -->
                    <div class="panel-body">
                        <div class="table-responsive">
                            <table class="table table-striped table-bordered table-hover">
                                <thead>
                                    <tr>
                                        <th>Date</th>
                                        <th>Time</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for approved_appointment in approved_appointments %}
                                    {% if user.student.id == approved_appointment.student_id %}
                                        <tr>
                                            <td>{{ approved_appointment.date }}</td>
                                            <td>{{ approved_appointment.time }}</td>
                                        </tr>
                                    {% endif %}
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                        <!-- /.table-responsive -->
                    </div>
                    <!-- /.panel-body -->
                </div>
                <!-- /.panel -->
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->

    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <b>All Appointments</b>
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered table-hover">
                            <thead>
                                <tr>
                                    <th>Sent Date</th>
                                    <th>Time</th>
                                    <th>Status</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for appointment in appointments %}
                                    {% if user.student.id == appointment.student_id %}
                                    <tr>
                                        <td>{{ appointment.date }}</td>
                                        <td>{{ appointment.time }}</td>
                                        <td>{{ appointment.approved }}</td>
                                    </tr>
                                    {% endif %}
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    <!-- /.table-responsive -->
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->

</div>
{% endblock %}

core/templates/core/dashboard/student/project_info.html
{% extends "core/dashboard/dashboard_base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div id="page-wrapper">
        <div class="row">
                <div class="col-lg-12">
                    <h2 class="page-header">Project</h2>
                </div>
                <!-- /.col-lg-12 -->
            </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <b>Project Information</b>
                    </div>
                    <!-- Panel Heading -->
    
                    <div class="panel-body">
                        <div class="panel">
                            <div class="panel-body">
                                {% if student.project %}
                                <table class="table table-hover table-striped bg-info table-bordered">
                                    <tbody>
                                        <tr>
                                            <td>Name of student :</td>
                                            <td>{{ student.first_name }} {{ student.last_name }}</td>
                                        </tr>
                                        <tr>
                                            <td>Name of supervisor :</td>
                                            <td>{{ student.supervisor.first_name }} {{student.supervisor.last_name }}</td>
                                        </tr>
                                        <tr>
                                            <td>Project title :</td>
                                            <td>{{ student.project.title }}</td>
                                        </tr>
                                        <tr>
                                            <td>Start date :</td>
                                            <td>{{ student.project.start_date }}</td>
                                        </tr>
                                        <tr>
                                            <td>Year :</td>
                                            <td> {{ student.project.schedule }} </td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <div class="col-lg-12">
                            <div class="panel panel-default">
                                <div class="panel-heading">
                                    Project Abstract
                                </div>
                                <div class="panel-body">
                                    <p>{{ student.project.abstract.abstract_text }}</p>
                                </div>
                            </div>
                        </div>
                        {% else %}
                        <div class="alert alert-danger alert-dismissable">
                                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                               You have not created a project yet. Fill in the form below to get started.
                        </div>
                        <form method="POST" action="{% url "create_project" %}" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="w-50 ml-5">
                            {{ form | crispy }}
                            <button class="btn btn-primary float-right pl-4 pr-4 mb-5" type="submit">Create Project</button>
                            <div class="clearfix"></div>
                            </div>
                        </form>

                        {% endif %}
                    </div>
                    <!-- /.panel-body -->
                </div>
                <!-- /.panel -->
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
    </div>

{% endblock %}

core/templates/core/dashboard/student/project_schedule.html
{% extends "core/dashboard/dashboard_base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h2 class="page-header">Schedule</h2>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-success">
                <div class="panel-heading">
                    <b>Project Schedule</b>
                </div>
                <!-- Panel Heading -->

                <div class="panel-body">

                    <div id="chart-1" class="">
                        {% if errors %}
                            {{errors}}
                        {% endif %}
                        {%if output %}
                            {{ output|safe }}
                        {% endif %}
                    </div>

                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
</div>

{% endblock %}

core/templates/core/dashboard/student/request_appointment.html
{% extends "core/dashboard/dashboard_base.html" %}

{% block content %}
{% load crispy_forms_tags %}

<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Request Appointment</h1>
        </div>        
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Request Appointment
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-12">
                            {%if errors%}
                                {{errors}}
                            {% else %}
                            <form action="{% url "request_appointment" %} " method="POST">
                                {% csrf_token %}
                                <div style="width:50%">
                                    <!-- <span><i id="clock" class="fa fa-clock-o"></i></span> -->
                                    {{ form|crispy }}
                                </div>
                                <button class="btn btn-success btn-md p-5">Request</button>
                            </form>
                            {% endif %}
                            </div>

                        </div>
                        </div>
                    </div>
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
        <!-- /.col-lg-12 -->
    </div>
</div>

{% endblock %}

{% block js %}

<script>
$(function () {
  $("#id_date").datetimepicker({
      format:"Y.m.d",
  });
  $("#id_time").datetimepicker({
      format:"H:i",
  });
  $('#clock').click(function(){
      $('#id_date').datetimepicker('show');
  });
});
</script>


{% endblock %}

core/templates/core/dashboard/student/view_available_slots.html
{% extends "core/dashboard/dashboard_base.html" %}

{% block content %}
<div id="page-wrapper">
        <div class="row">
                <div class="col-lg-12">
                    <h2 class="page-header">Appointments</h2>
                </div>
                <!-- /.col-lg-12 -->
            </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <b>Available time slots for supervision by {{ user.student.supervisor.first_name }} {{ user.student.supervisor.last_name }}</b>
                    </div>
                    <!-- Panel Heading -->
    
                    <div class="panel-body">
                        <div class="table-responsive">
                            <table class="table table-striped table-bordered table-hover">
                                <thead>
                                    <tr>
                                        <th>Day</th>
                                        <th>Time</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for day in days %}
                                    <tr>
                                        <td>Monday </td>
                                        <td>{{ day.monday }}</td>
                                    </tr>
                                    <tr>
                                        <td>Tuesday</td>
                                        <td>{{ day.tuesday }}</td>
                                    </tr>
                                    <tr>
                                        <td>Wednesday</td>
                                        <td>{{ day.wednesday }}</td>
                                    </tr>
                                    <tr>
                                        <td>Thursday</td>
                                        <td>{{ day.thursday }}</td>
                                    </tr>
                                    <tr>
                                        <td>Friday</td>
                                        <td>{{ day.friday }}</td>
                                    </tr>
                                    <tr>
                                        <td>Saturday</td>
                                        <td>{{ day.saturday }}</td>
                                    </tr>
                                    <tr>
                                        <td>Sunday</td>
                                        <td>{{ day.sunday }}</td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                        <!-- /.table-responsive -->
    
                    </div>
                    <!-- /.panel-body -->
                </div>
                <!-- /.panel -->
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
    </div>

{% endblock %}